spring:
#   应用名称
  application:
    name: AICodeBackend
#    MySQL配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/ai_code
    username: root
    password: 1234
#    Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234
  #  开启本地配置文件
  profiles:
    active: local
  # LangChain4j 独立配置（部分新版本支持）
langchain4j:
  community:
    redis:
      host: localhost
      port: 6379
      password: 1234
      ttl: 3600
#    服务器配置
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.hbpu.aicodebackend.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
ai:
  reasoning:
    is-reasoning-model: false   # true = deepseek-reasoner，false = deepseek-chat
# mermaid配置
mermaid:
  puppeteer-config-path: D:\IDEAProject\AICodeBackend\puppeteer-config.json