spring:
  #   应用名称
  application:
    name: ai-code-screenshot
  #  开启本地配置文件
  profiles:
    active: local
#    服务器配置
server:
  port: 8127
  servlet:
    context-path: /api
# Dubbo
dubbo:
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
    register-mode: instance
  protocol:
    name: tri
    port: 50052
  consumer:
    timeout: 120000
  provider:
    timeout: 120000
